// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB53eLjwJRcVI1M_yCN5CiX_bp_OdwPSaA',
    appId: '1:134403906802:android:714e7d8dede967a95c846b',
    messagingSenderId: '134403906802',
    projectId: 'todoriverpod-1547b',
    databaseURL: 'https://todoriverpod-1547b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoriverpod-1547b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3qLk72uQnNYTZe9Pt4L-0tvLTxkkHZxY',
    appId: '1:134403906802:ios:9aa4e5da7eeba1065c846b',
    messagingSenderId: '134403906802',
    projectId: 'todoriverpod-1547b',
    databaseURL: 'https://todoriverpod-1547b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoriverpod-1547b.appspot.com',
    iosBundleId: 'com.example.riverpodTodoApp',
  );
}
